### ISSUE TITLE
plotRateSpectrogram 

### ISSUE THREAD

**Issue by AhmedHamdy-e21** [suny-downstate-medical-center/netpyne#727]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_1025/1366540568.py in <module>
----> 1 sa.plotRateSpectrogram();

AttributeError: module 'netpyne.analysis' has no attribute 'plotRateSpectrogram'

**Comment by vvbragin** [comment]
The following flow should work in NetPyNE v1.0.4.2:
```
from netpyne import sim
# ... load data / simulate
sa = sim.analysis
sa.plotRateSpectrogram()
```
